# Generated by Django 5.1.4 on 2025-01-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('common_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='hogwarts_app.locations')),
                ('head_of_the_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='hogwarts_app.professors')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='hogwarts_app.houses')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='hogwarts_app.locations')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Students_to_subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_to_subjects', to='hogwarts_app.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_to_subjects', to='hogwarts_app.subjects')),
            ],
            options={
                'verbose_name': 'Students_to_subjects',
                'verbose_name_plural': 'Students_to_subjects',
            },
        ),
        migrations.AddField(
            model_name='professors',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='hogwarts_app.subjects'),
        ),
    ]
